[package]
name = "mhw_toolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.21", optional = true }
mlua = { version = "0.9.7", features = ["lua54", "vendored"], optional = true }
once_cell = "1.19.0"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
winapi = { version = "0.3.9", features = ["winuser", "stringapiset", "winnls"] }
tokio = { version = "1.37.0", features = ["full"], optional = true }
windows = { version = "0.56.0", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
] }
minhook-sys = { version = "0.1.1", optional = true }
thiserror = "1.0.59"

[features]
default = []
lua_engine = ["mlua"]
logger = ["log"]
async-tokio = ["tokio"]
hooks = ["minhook-sys"]
