use strum::EnumString;

#[repr(isize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, EnumString)]
pub enum HUEAbnormality {
    SelfImprovement = 0x38,
    AttackUp = 0x3C,
    AttackUpL = 0x40,
    HealthBoost = 0x44,
    HealthBoostL = 0x48,
    StaminaUseRed = 0x4C,
    StaminaUseRedL = 0x50,
    WindPressure = 0x54,
    WindPressurePlus = 0x58,
    DefenseUp = 0x5C,
    DefenseUpL = 0x60,
    ToolUseRed = 0x64,
    ToolUseRedL = 0x68,
    HealthRec = 0x80,
    HealthRecL = 0x84,
    Earplug = 0x88,
    EarplugPlus = 0x8C,
    DivineProtection = 0x90,
    Scoutfly = 0x94,
    EnvNeg = 0x98,
    StunNeg = 0x9C,
    ParalysisNeg = 0xA0,
    TremorsNeg = 0xA4,
    DeepResistance = 0xA8,
    FireResistance = 0xAC,
    FireResistanceL = 0xB0,
    WaterResistance = 0xB4,
    WaterResistanceL = 0xB8,
    ThunderResistance = 0xBC,
    ThunderResistanceL = 0xC0,
    IceResistance = 0xC4,
    IceResistanceL = 0xC8,
    DragonResistance = 0xCC,
    DragonResistanceL = 0xD0,
    ElementalAttackUp = 0xD4,
    BlightNeg = 0xD8,
    KnockbackNeg = 0xE4,
    AllResUp = 0xEC,
    AffinityUp = 0xF0,
    AilmentsNeg = 0xF4,
    Earplug2 = 0xF8,
    AbnormAttackUp = 0xFC,
    MaxStamRecovery = 0x10C,
    ExtHealthRecovery = 0x110,
    SpeedEvadeUp = 0x114,
    AllResElementAttack = 0x118,
}

#[repr(isize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, EnumString)]
pub enum PalicoAbnormality {
    Resuscitate = 0x11C,
    AttackUp = 0x120,
    AttackUpL = 0x124,
    DefenseUp = 0x128,
    DefenseUpL = 0x12C,
    AffinityUp = 0x130,
    HealthRec = 0x134,
    HealthBoost = 0x138,
    StaminaUseRed = 0x13C,
    DivineProtection = 0x148,
    StunNeg = 0x14C,
    ParalysisNeg = 0x150,
    TremorsNeg = 0x154,
    EARPLUG = 0x158,
    Windproof = 0x15C,
    EnvNeg = 0x160,
}
